### ISSUE TITLE
Add raster and vector cut in the in same job

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#105]
At the moment this need to be done separately.  
If svg color detection is also integrated that would be awesome. 
Could be a good enhancement and makes the process easier.

**Comment by ghost** [comment]
We cannot raster SVGs (note how its absent from the Raster menu filetypes under the accept= near the end of line https://github.com/openhardwarecoza/LaserWeb/blob/master/i/index.html#L188)  and similarly we cannot vector cut from bitmaps.,. So you would still need to load two files. 

loading two files leads to offset and positioning issues.

So handling it as seperate tasks would be the most reliable way of doing this since you can zero out between operations, check where its going to do what using the Bounding Box, etc

**Comment by funinthefalls** [comment]
I create a master file in Inkscape that has both the raster and vector components, separate them into 2 different layers. Then I output 2 separate gcode file s, one for raster, one for vector.  Run the raster first , do not move the workpiece, then run the vector. Siunce both gcode files were created from the same master file, as long as you do not move the workpiece there will not be any alignment issues.

**Comment by cojarbi** [comment]
Thanks @funinthefalls.  I this the way the industry handles this?

**Comment by funinthefalls** [comment]
Not sure, that is just the way I do it.
