### ISSUE TITLE
Unable to move raster in Y axis

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#44]
I can move the preview in X but not in Y
See video https://plus.google.com/+ArielYahni/posts/Rz5ezxhRvYN

**Comment by cojarbi** [comment]
I added my own image and it came in in negative Y, but i waas able to move it in positive Y. Note the case when imported the gcode you sent
<img width="1831" alt="screen shot 2016-01-05 at 12 00 23 am" src="https://cloud.githubusercontent.com/assets/16444438/12107982/d7d93b20-b33f-11e5-917f-2d5cf7a22285.png">

**Comment by ghost** [comment]
Thats one of the known bugs I mentioned on Google Plus last night.

There was three, I tacklet the laser power scaling bug first this morning, havent gotten to that one yet.  The bug is that the Physical image size (needed to offset it from the negative) only gets calculated ff you change the Spot Size  before clicking Raster Now

**Comment by ghost** [comment]
And this bug is fixed:

https://github.com/openhardwarecoza/LaserWeb/commit/a77c3833b8f430e7794526fced8bd129548f6475

**Comment by ghost** [comment]
![simplified](https://cloud.githubusercontent.com/assets/7695323/12120277/d42f7748-b3d8-11e5-88cf-6e22c80e002a.png)

Simplified the UI while I was at it...
