### ISSUE TITLE
Issue opening DFX and then canceling to open another

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#48]
I go and select a DFX file but immediately press the x in the right corner to cancel and be able to select another file. Once i select the other file it will not show the dialog anymore. I need to refresh the page to start over.

**Comment by ghost** [comment]
Fixed.   Clearing the fileInputGcode input field right after opening instead of after processing. 

```
    document.getElementById('fileInputGcode').value = '';
```

It uses the "change" event to launch the Cutting Params at  https://github.com/openhardwarecoza/LaserWeb/blob/master/i/main.js#L1076, and by clearing it, opening the same file again, counts as a change (:
