### ISSUE TITLE
Smoothie with dual pin (non pwm)  supplies 

### ISSUE THREAD

**Issue by ghost** [openhardwarecoza/LaserWeb#54]
Need to add m3/m5 in LaserWeb's smoothie code too for users with two pin config (pwm into IN via capacitor + TH/TL on a smootie switch pin) 

Thanks to https://github.com/TurnkeyTyranny/laser-gcode-exporter-inkscape-plugin/pull/8 for bringing to my attention

**Comment by ajfoul** [comment]
Please note that Smoothie config will be need to have a switch to enable M3/M5 to fire. I've got a [sample here](https://gist.github.com/ajfoul/b32a0432f337e81f3ab6) (pin assignments may need to be adjusted depending on board and wiring)

And, all the two pin PSUs I've seen do PWM on IN.  In some cases a logic level shifter is needed because some PSUs don't support Smoothie's 3.3v logic.

**Comment by ghost** [comment]
(: I have the level converters in my board, and we have it documented nicely on the SmoothK40 Wiki entry too:   http://smoothieware.org/blue-box-guide 

Thanks for the sample config. Will update the Wiki tonight

**Comment by prcdslnc13** [comment]
This just answered my biggest question on how to wire all this up. Thanks
for the post.

On Wed, Jan 13, 2016 at 1:54 AM, Peter van der Walt <
notifications@github.com> wrote:

> (: I have the level converters in my board, and we have it documented
> nicely on the SmoothK40 Wiki entry too:
> http://smoothieware.org/blue-box-guide
> 
> Thanks for the sample config. Will update the Wiki tonight
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openhardwarecoza/LaserWeb/issues/54#issuecomment-171209176
> .

## 

Thanks,
Joe Spanier

```
       "*No Trees were harmed in the sending of this email, but a great
```

number of electrons were terribly inconvenienced" *

**Comment by ghost** [comment]
Available as configurable option in LaserWeb2 - so closing this one
