### ISSUE TITLE
Frame around object on SVG load

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#57]
As i load and SVG a frame is made around the drawing. it seems as if laserweb is reading the page itself from inkscape. 
[test copy.svg.txt](https://github.com/openhardwarecoza/LaserWeb/files/91351/test.copy.svg.txt)
<img width="1820" alt="screen shot 2016-01-14 at 11 02 29 pm" src="https://cloud.githubusercontent.com/assets/16444438/12345180/607512b2-bb13-11e5-99c7-107d8ec39475.png">

**Comment by ghost** [comment]
Yes, thats documented (which is why I added the DPI buttons to get a more accurate size

SVG sucks in that all positions are relative to the document.  Same is true for DXF.  Its great since it allows you to do multi pass jobs with a common 0 point.
1.  In your SVGs make your document properties the size of your laser (or the default 600x400 laserweb uses)
2. Position your artwork relative to bottom left corner 
3.  When importing to laserweb, dont bother with the slider - just use the DPI buttons to get it accurate

**Comment by cojarbi** [comment]
Noted

**Comment by ghost** [comment]
I am going to add the dpi buttons to raster too.    Accurate dimensions will be easier than the sliders
